In [1]:
import numpy as np

In [16]:
data1=[6,7.5,8,0,1]

In [17]:
arr1 = np.array(data1)

In [18]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
arr1.shape

(5,)

In [20]:
data2 =[[1,2,3,4],[5,6,7,8]]

In [21]:
arr2 = np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.shape

(2, 4)

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr=np.array([1,2,3,4,5],dtype=np.int64)

In [30]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr

array([1., 2., 3., 4., 5.])

In [35]:
float_arr.dtype

dtype('float64')

In [36]:
arr1 = np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [38]:
arr2 = np.array([[7,8,9],[10,11,12]],dtype=np.float64)

In [39]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
arr1+arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr1-arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [43]:
arr1*arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

곱셈은 행렬의 곱셈과 다른 것이다. 그냥 그 자리에 있는 애들을 곱한다.

In [44]:
arr1/arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [45]:
arr1 *2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [46]:
arr ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [47]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

array의 대한 연산은 각 성분에대해 각각 이루어 진다.