In [16]:
import numpy as np

In [17]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[5]

5

In [20]:
arr[5:8]

array([5, 6, 7])

In [21]:
arr[5:8]=12

In [22]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

In [25]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [26]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [30]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [31]:
arr2d[3,2]

15

In [32]:
arr2d[:2,1:3]=0

In [33]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
data=np.random.randn(7,4)

In [35]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], dtype='<U7')

In [37]:
data

array([[ 0.13819419,  0.19350215,  0.06391676,  0.63996596],
       [-0.30141822,  0.45917329, -0.31620394, -1.51446598],
       [ 0.71362551, -0.04479039, -1.7838209 , -0.75304712],
       [ 0.24746419, -0.19994284, -1.35540579,  0.20645982],
       [-0.17591699, -1.42262167, -0.21422059, -1.99845188],
       [ 0.69183858, -0.29670931, -0.44940527,  0.72996574],
       [ 1.77892895,  1.03889275,  1.69854954, -0.08236818]])

In [38]:
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [40]:
data[names=="Charles"]

array([[ 0.13819419,  0.19350215,  0.06391676,  0.63996596],
       [ 0.24746419, -0.19994284, -1.35540579,  0.20645982]])

In [41]:
data[names=="Kilho",:]

array([[-0.30141822,  0.45917329, -0.31620394, -1.51446598],
       [ 0.69183858, -0.29670931, -0.44940527,  0.72996574],
       [ 1.77892895,  1.03889275,  1.69854954, -0.08236818]])

In [45]:
data[(names=="Charles") | (names=="Kilho")]

array([[ 0.13819419,  0.19350215,  0.06391676,  0.63996596],
       [-0.30141822,  0.45917329, -0.31620394, -1.51446598],
       [ 0.24746419, -0.19994284, -1.35540579,  0.20645982],
       [ 0.69183858, -0.29670931, -0.44940527,  0.72996574],
       [ 1.77892895,  1.03889275,  1.69854954, -0.08236818]])

In [46]:
data[:,3]

array([ 0.63996596, -1.51446598, -0.75304712,  0.20645982, -1.99845188,
        0.72996574, -0.08236818])

In [47]:
data[:,3]<0

array([False,  True,  True, False,  True, False,  True])

In [48]:
data[data[:,3]<0,:]

array([[-0.30141822,  0.45917329, -0.31620394, -1.51446598],
       [ 0.71362551, -0.04479039, -1.7838209 , -0.75304712],
       [-0.17591699, -1.42262167, -0.21422059, -1.99845188],
       [ 1.77892895,  1.03889275,  1.69854954, -0.08236818]])

In [49]:
data[data[:,3]<0,:] =0

In [50]:
data

array([[ 0.13819419,  0.19350215,  0.06391676,  0.63996596],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.24746419, -0.19994284, -1.35540579,  0.20645982],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.69183858, -0.29670931, -0.44940527,  0.72996574],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])