In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1.제곱근

In [4]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

2.log10

In [5]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

3.array각 성분에 적용되는 함수

abs	:각 성분의 절댓값 계산

sqrt :각 성분의 제곱근 계산 (array ** 0.5 의 결과와 동일)

square	:각 성분의 제곱 계산 (array ** 2 의 결과와 동일)

exp	:각 성분을 무리수 e의 지수로 삼은 값을 계산

log, log10, log2 :자연로그(밑이 e), 상용로그(밑이 10), 밑이 2인 로그를 계산

sign :각 성분의 부호 계산 (+인 경우 1, -인 경우 -1, 0인 경우 0)

ceil :각 성분의 소수 첫 번째 자리에서 올림한 값을 계산

floor :각 성분의 소수 첫 번째 자리에서 내림한 값을 계산

isnan :각 성분이 NaN(Not a Number)인 경우 True를, 그렇지 않은 경우 False를 반환

isinf :각 성분이 무한대(infinity)인 경우 True를, 그렇지 않은 경우 False를 반환

cos, cosh, sin, sinh, tan, tanh	:각 성분에 대한 삼각함수 값을 계산


4.두개의 random array

In [6]:
x= np.random.randn(8)
y= np.random.randn(8)

In [7]:
x

array([-0.33045822, -0.48186506, -0.44686198, -0.45617275,  0.53592395,
        0.18738747, -0.74192721,  0.26550797])

In [8]:
y

array([-0.74641929, -0.25500863, -0.37908164, -0.66571425, -0.13889632,
        0.42575352, -0.04246259, -0.62002189])

4-1.두 array 값중 max

In [9]:
np.maximum(x,y)

array([-0.33045822, -0.25500863, -0.37908164, -0.45617275,  0.53592395,
        0.42575352, -0.04246259,  0.26550797])

In [13]:
arr=np.random.randn(5,4)

In [14]:
arr


array([[ 0.24560401,  0.5149942 ,  0.99651102,  0.30828409],
       [ 0.12099537,  0.27309767,  0.22969845, -0.37640595],
       [ 0.57224796, -0.06576678,  2.24247206,  1.73794682],
       [-0.35086097, -1.90159239, -0.85028363,  0.23548014],
       [-0.0539436 , -0.54439576,  1.89953724,  0.13675389]])

5.두개의 array에 적용되는 함수

add :두 array에서 동일한 위치의 성분끼리 더한 값을 계산 (arr1 + arr2의 결과와 동일)

subtract :두 array에서 동일한 위치의 성분끼리 뺀 값을 계산 (arr1 - arr2의 결과와 동일)

multiply :두 array에서 동일한 위치의 성분끼리 곱한 값을 계산 (arr1 * arr2의 결과와 동일)

divide :두 array에서 동일한 위치의 성분끼리 나눈 값을 계산 (arr1 / arr2의 결과와 동일)

maximum	:두 array에서 동일한 위치의 성분끼리 비교하여 둘 중 최댓값을 반환

minimum	:두 array에서 동일한 위치의 성분끼리 비교하여 둘 중 최솟값을 반환

6.array의 총합

In [15]:
arr.sum()

5.370373821962306

7.array의 평균

In [16]:
arr.mean()

0.2685186910981153

8.각 열에 대한 합의 계산

In [17]:
arr.sum(axis=0)

array([ 0.53404277, -1.72366307,  4.51793513,  2.04205899])

9.각 행에 대한 합의 계산

In [19]:
arr.sum(axis=1)

array([ 2.06539332,  0.24738554,  4.48690005, -2.86725685,  1.43795177])

10.array에 적용되는 통계함수

sum :전체 성분의 합을 계산

mean :전체 성분의 평균을 계산

std, var :전체 성분의 표준편차, 분산을 계산

min, max :전체 성분의 최솟값, 최댓값을 계산

argmin, argmax :전체 성분의 최솟값, 최댓값이 위치한 인덱스를 반환

cumsum :맨 첫번째 성분부터 각 성분까지의 누적합을 계산 (0에서부터 계속 더해짐)

cumprod :맨 첫번째 성분부터 각 성분까지의 누적곱을 계산 (1에서부터 계속 곱해짐)

In [21]:
arr>0

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True]])

In [22]:
(arr>0).sum()

13

arr의 각 값이 0보다 큰것이 true로 나타나는 mask를 만든뒤 sum()을 사용하게 되면 영보다 큰 수의 갯수를 알 수 있다.

11.정렬함수

In [24]:
arr = np.random.randn(8)

In [25]:
arr

array([-0.11583567, -0.82605662,  1.32046345,  1.25562486, -0.66946327,
       -1.3351781 ,  0.50163571, -0.94830694])

11-1.오름차순 정렬

In [26]:
np.sort(arr)

array([-1.3351781 , -0.94830694, -0.82605662, -0.66946327, -0.11583567,
        0.50163571,  1.25562486,  1.32046345])

11-2.내림차순 정렬

In [27]:
np.sort(arr)[::-1]

array([ 1.32046345,  1.25562486,  0.50163571, -0.11583567, -0.66946327,
       -0.82605662, -0.94830694, -1.3351781 ])

In [29]:
arr = np.random.randn(5,3)

In [30]:
arr

array([[-0.18554963,  0.05921168, -1.05919221],
       [-1.65296912, -1.58603632,  0.34041826],
       [ 1.94176935, -0.90940176,  0.77496572],
       [ 1.3160942 , -1.44712503, -0.31152352],
       [ 0.43501267, -0.35227319,  1.31341894]])

11-3.각 열의(2차원) 오름차순 정렬

In [31]:
np.sort(arr, axis=0)

array([[-1.65296912, -1.58603632, -1.05919221],
       [-0.18554963, -1.44712503, -0.31152352],
       [ 0.43501267, -0.90940176,  0.34041826],
       [ 1.3160942 , -0.35227319,  0.77496572],
       [ 1.94176935,  0.05921168,  1.31341894]])

11-4.각 행의(2차원) 오름차순 정렬

In [32]:
np.sort(arr, axis=1)

array([[-1.05919221, -0.18554963,  0.05921168],
       [-1.65296912, -1.58603632,  0.34041826],
       [-0.90940176,  0.77496572,  1.94176935],
       [-1.44712503, -0.31152352,  1.3160942 ],
       [-0.35227319,  0.43501267,  1.31341894]])

서로다른 행과 열사이의 성분이 섞일 수 있음을 염두한다.

11-5.상위 a%의 값 가져오기

In [35]:
large_arr=np.random.randn(150)

In [36]:
large_arr

array([ 1.89195478,  0.28793701, -1.44568243, -0.54756004, -0.11631534,
        1.03117158,  0.01972998, -0.79258451, -0.77993469,  1.17706674,
       -0.99680383, -1.78887553, -0.40799422, -1.35805555,  0.87323332,
        0.86962662, -0.03793947, -0.14660185, -0.75853418,  0.55890472,
       -1.70580302, -0.38844494, -0.3695127 , -0.06543088,  0.64075854,
       -2.01584329, -1.20671074,  0.97035434,  0.0719262 ,  2.09831455,
        0.642321  , -1.33360864, -0.12166858,  2.81319253,  1.17570245,
        0.61598601, -1.29563019,  0.33698424,  1.11712634,  0.47458029,
        1.53947869, -0.56507645,  0.52461291, -0.22714708,  1.25473181,
        0.04267642,  0.33098065, -0.34885268, -0.10246582,  1.28942718,
       -0.21528172,  1.18160617,  0.66487232, -0.62167451, -1.16394827,
       -1.43278101,  1.24099913,  0.66597876,  0.45835066, -0.27305618,
        1.08036834,  0.81572792,  1.16405035,  1.9654058 ,  0.23997934,
        2.58526907,  0.59978483, -0.51617245,  1.69509053,  1.63

In [38]:
np.sort(large_arr)[::-1]

array([ 2.81319253,  2.58526907,  2.13568726,  2.09831455,  2.03706369,
        2.03503469,  1.9654058 ,  1.95072799,  1.89195478,  1.84639417,
        1.80820401,  1.74717023,  1.72621475,  1.72450481,  1.69509053,
        1.66604929,  1.63131114,  1.57115147,  1.53947869,  1.28942718,
        1.25473181,  1.24099913,  1.23671691,  1.1889497 ,  1.18160617,
        1.18105172,  1.17706674,  1.17641812,  1.17570245,  1.16405035,
        1.11712634,  1.10547738,  1.08036834,  1.03117158,  0.98211454,
        0.97035434,  0.96143874,  0.87323332,  0.86962662,  0.84358681,
        0.81572792,  0.67777125,  0.66597876,  0.66487232,  0.642321  ,
        0.64075854,  0.61598601,  0.60183533,  0.59978483,  0.56587643,
        0.55890472,  0.52461291,  0.47458029,  0.46823639,  0.45835066,
        0.44904781,  0.36050787,  0.33698424,  0.3364556 ,  0.33098065,
        0.30985742,  0.28793701,  0.28694402,  0.26231215,  0.24347534,
        0.23997934,  0.18485761,  0.1828134 ,  0.16373272,  0.13

In [39]:
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]

1.9507279902878814

len(large_arr)로 array의 길이(150)를 구한뒤 0.05를 곱한 값에 int()를 씌워주면 상위 5%에 해당하는 index를 얻을 수 있다. 내림차순으로 정렬된 array에 적용해주면 그 index에 해당하는 값을 보여줄 것이다.

In [41]:
names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
ints = np.array([3,3,3,2,2,1,1,4,4])

12.uniqueg한 값 뽑아내기

In [42]:
np.unique(names)

array(['Charles', 'Hayoung', 'Kilho'], dtype='<U7')

In [43]:
np.unique(ints)

array([1, 2, 3, 4])