In [1]:
import numpy as np

data file 중 , 를 구분자로 가지는 파일을 csv파일이라고 칭한다.

In [5]:
data = np.loadtxt("C:/Users/user/flearning_da/data/ratings.dat",delimiter="::", dtype=np.int64)

loadtxt() 함수는 data set을 불러들여와 array형태로 저장해준다.

In [25]:
#data를 잘 읽어 들였나 확인

In [8]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [11]:
data.shape

(1000209, 4)

In [15]:
#전체 평균 평점 계산하기
mean_rating_total = data[:,2].mean()

In [18]:
mean_rating_total

3.581564453029317

In [22]:
#각 사용자 별 평균 평점 계산하기
user_ids = np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [23]:
user_ids.shape

(6040,)

In [30]:
mean_rating_by_user_list = []
for user_id in user_ids:
    data_for_user = data[data[:,0]==user_id, :]
    mean_rating_for_user = data_for_user[:,2].mean()
    mean_rating_by_user_list.append([user_id,mean_rating_for_user])

data[:,0]==user_id: data array에서 0번 index 에 해당하는 1열을 추출해준 다음에 그 추출된 1열에 대해서 이것이 user_id와 같다는 형태로 써주면 boolian mask가 생성된다. 

data_for_user = data[data[:,0]==user_id,:] : 이렇게 mask가 생성되면 data array의 행부분으로 하고 전체열을 선택하면 현재 조사하고 있는 user id의 모든 행을 추출할 수 있다. 그 행으로 구성된 array를 data_for_user로 저장 

mean_rating_for_user = data_for_user[:,2].mean() : mean_rating_for_user에는 현재 우리가 조사하고 있는 id의 평점이 저장되게 되는 것이다. 

mean_rating_by_user_list.append([user_id,mean_rating_for_user]) : 그 각각의 list를 새 list에 저장하는 것이다.

In [32]:
mean_rating_by_user_list[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [38]:
mean_rating_by_user_array = np.array(mean_rating_by_user_list, dtype=np.float32)

In [39]:
mean_rating_by_user_array[:5]

array([[1.       , 4.188679 ],
       [2.       , 3.7131784],
       [3.       , 3.9019608],
       [4.       , 4.1904764],
       [5.       , 3.1464646]], dtype=float32)

In [40]:
mean_rating_by_array.shape

(6040, 2)

txt파일로 저장한다.

In [47]:
np.savetxt("mean_rating_by_user.csv", mean_rating_by_user_array,fmt='%.3f', delimiter=',')

SyntaxError: invalid syntax (<ipython-input-49-f188d5ac1197>, line 1)